#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# Install the phaze compiler
#------------------------------------------------------------------------------#

# request install directory
echo "Installation directory [/opt/phaze]:"

# read input
read -e path

if [ -z "$path" ] ; then
	path=/opt/phaze
fi

echo "Installing to $path"

bindir=$path/bin
jardir=$path/jar
sampledir=$path/samples
sharedir=$path/share

# create directories
mkdir -p $bindir
mkdir -p $jardir
mkdir -p $sampledir
mkdir -p $sharedir

# create phaze script
cat bin/phaze.in | sed "s,@PATH@,$path,g" > $bindir/phaze
chmod 755 $bindir/phaze

# copy jar file
cp jar/phaze.jar $jardir

# copy samples
cp samples/* $sampledir

# copy share
cp -r share/* $sharedir

# finished
echo "Installation Complete!"
echo "Please add $bindir to your PATH"
