/*----------------------------------------------------------------------------*
 * PhazeBoilerPlate
 *----------------------------------------------------------------------------*/

package Phaze;

public class PhazeBoilerPlate {

	public static final String commentLineStart =
		"/*--------------------------------------" +
		"--------------------------------------*\n";

	public static final String commentLineEnd =
		" *--------------------------------------" +
		"--------------------------------------*/\n";

	public static final String genericHeader = commentLineStart +
		" * Copyright (c) 2012 Los Alamos National Security, LLC\n" +
		" * All rights reserved.\n" +
		" *\n" +
		" * DO NOT EDIT! THIS FILE WAS GENERATED BY PHAZE\n" +
		" *\n" +
		" * %s\n" + commentLineEnd;

} // class PhazeBoilerPlate
