#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

#------------------------------------------------------------------------------#
# Generate Makefile.am in lib directory
#------------------------------------------------------------------------------#
echo "Generating lib/Makefile.am"
[ ! -d lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

#------------------------------------------------------------------------------#
# Call libtoolize
#------------------------------------------------------------------------------#
echo "Calling libtoolize..."
# check for glibtoolize
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize

# actually call libtoolize
$LIBTOOLIZE -c -f --automake

#------------------------------------------------------------------------------#
# Call aclocal
#------------------------------------------------------------------------------#
echo "Calling aclocal"
aclocal > /dev/null 2>&1

#------------------------------------------------------------------------------#
# Call automake
#------------------------------------------------------------------------------#
echo "Calling automake -af --foreign"
automake -af --foreign -c

#------------------------------------------------------------------------------#
# Call autoconf
#------------------------------------------------------------------------------#
echo "Calling autoconf"
autoconf
