#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

config/clean_ac

rm -rf bin
rm -rf config
rm -rf configure.ac
rm -rf lib
rm -rf Makefile.am
rm -rf README
rm -rf src
